baseURL = "https://javierrodriguez78.github.io"
languageCode = "en-us"
title = "Javier Rodríguez"
theme = "hugo-theme-cleanwhite"
publishDir = "docs"

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/home-bg-jeep.jpg"